services:
  # Webサービス
  - type: web
    name: goods-planner
    env: docker
    buildCommand: ./bin/render-build.sh
    dockerfilePath: Dockerfile
    dockerCommand: bundle exec rails server -b 0.0.0.0
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /up
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: goods-planner-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"

# データベース
databases:
  - name: goods-planner-db
    plan: free
    databaseName: goods_planner_production
    user: goods_planner
    